services:
  - type: web
    name: notegpt
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: notegpt-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false

databases:
  - name: notegpt-db
    databaseName: notegpt
    user: notegpt
    plan: free