name = "notegpt"
main = "dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production]
name = "notegpt-production"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"

[env.staging]
name = "notegpt-staging"

[vars]
NODE_ENV = "production"
PORT = "8787"
