name = "notegpt"
main = "dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"

[env.production]
name = "notegpt-production"

[env.staging]
name = "notegpt-staging"

[vars]
NODE_ENV = "production"
PORT = "8787"

# KV namespaces (optional)
# [[kv_namespaces]]
# binding = "NOTES_KV"
# id = "your-kv-id"
# preview_id = "your-preview-kv-id"
