name = "notegpt"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build && npx esbuild server/worker.ts --platform=neutral --packages=external --bundle --format=esm --outfile=dist/worker.js --define:import.meta.dirname='\"./\"'"

[env.production]
name = "notegpt-production"

[env.staging]
name = "notegpt-staging"

[vars]
NODE_ENV = "production"